name: FriCAS CI on Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install sbcl libgmp-dev libxpm-dev
    - name: configure
      run: ./configure --with-lisp=sbcl --with-gmp --with-x || cat config.log
    - name: make
      run: make -j2 --output-sync
    - name: make check
      run: make check -j2 --output-sync
