name: FriCAS CI on macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-12
    timeout-minutes: 30
    env:
      SBCL_VER: 2.2.9

    steps:
    - uses: actions/checkout@v3
    - name: download and unpack SBCL
      run: |
        wget https://downloads.sourceforge.net/project/sbcl/sbcl/${SBCL_VER}/sbcl-${SBCL_VER}-x86-64-darwin-binary.tar.bz2
        tar xvf sbcl-${SBCL_VER}-x86-64-darwin-binary.tar.bz2
    - name: configure
      run: |
        mkdir ../build && cd ../build
        ../fricas/configure --with-lisp=${GITHUB_WORKSPACE}/sbcl-${SBCL_VER}-x86-64-darwin/run-sbcl.sh --enable-gmp || cat config.log
    - name: make
      run: cd ../build && make -j3
    - name: make check
      run: cd ../build && make check -j3
    - name: Create artifact archives
      run: |
        cd ../build
        make dist-macos
        cp -v `brew list gmp | grep libgmp.10.dylib` FriCAS.app/Contents/Resources/usr/local/lib/fricas/target/*/lib/
        make dist-macos-dmg
        mv FriCAS.dmg ../fricas/FriCAS-macOS-x86_64-${{ github.sha }}.dmg
    - name: Upload macOS binary
      uses: actions/upload-artifact@v3
      with:
        name: FriCAS-macOS-x86_64-binary
        path: FriCAS-macOS-x86_64-${{ github.sha }}.dmg
    - name: Upload to nightly release
      if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/master' && github.repository == 'fricas/fricas' }}
      run: |
        export OWNER_REPO=fricas/fricas-nightly-builds
        export RELEASE_ID=74905307 ## `curl https://api.github.com/repos/${OWNER_REPO}/releases/tags/nightly | jq .id`
        curl -v -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.releasetoken }}" "https://uploads.github.com/repos/${OWNER_REPO}/releases/${RELEASE_ID}/assets?name=FriCAS-$(date +%Y-%m-%dT%H.%M)-macOS-x86_64-$(echo ${{ github.sha }} | cut -c 1-8).dmg" --data-binary "@FriCAS-macOS-x86_64-${{ github.sha }}.dmg" -H "Content-Type: application/x-apple-diskimage" || true
